services:
  api1: &api1
    hostname: api1
    build: ./src
    depends_on:
      redis:
        condition: service_healthy
    environment:
      ConnectionStrings__Redis: redis://redis:6379
      PaymentProcessorDefault__BaseUrl: http://payment-processor-default:8080
      PaymentProcessorFallback__BaseUrl: http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "165MB"
  
  api2:
    <<: *api1
    hostname: api2
    depends_on:
      redis:
        condition: service_healthy
    environment:
      ConnectionStrings__Redis: redis://redis:6379
      PaymentProcessorDefault__BaseUrl: http://payment-processor-default:8080
      PaymentProcessorFallback__BaseUrl: http://payment-processor-fallback:8080

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "20MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true